---
title: "cyanoFilter"
subtitle: "An Automated Framework for Identifying synechoccus type cyanobacteria population in Flow Cytometry"
author: "Olusoji O. D., De Laender F., Spaak J., Neyens T., Aerts M."
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

metadata <- system.file("extdata", "2019-03-25_Rstarted.csv", package = "cyanoFilter", 
                        mustWork = TRUE)
```

## Introduction

Flow cytometry is a well-known technique for identifying cell populations. It is largely applied in biomedical and medical sciences for cell sorting, counting, biomarker detections and protein engineering. The technique also provides an energy efficient alternative to microscopy that has long been the standard technique for cell population identification. Cyanobacteria are bacteria phylum believe to contribute more than 50% of atmospheric oxygen via oxygen and are found almost everywhere. These bacteria are also one of the known oldest life forms known to obtain their energy via photosynthesis.

## Exisitng methods for identifying cell populations in flow cytometry

## Crucial Synechococcus Properties

## Software

## Illustrations

## Discussions

## Acknowledgements



